# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv load_addr "0x9000000"
setenv overlay_error "false"
# default values
# Same as Rock 3A / boot-rk35xx.cmd (load_addr=0x9000000). No OP-TEE packed.
# U-Boot bootflow loads this as FAT boot.scr (BOOTMETH_SCRIPT) — keep it correct
# on eMMC when refreshing U-Boot alone: also rewrite /boot/boot.scr from this file.
setenv rootdev ""
# Mainline / Rock 3A style: console=ttyS2 (needs kernel DTS: fiq-debugger off, &uart2 on).
setenv verbosity "7"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "on"

test -n "${distro_bootpart}" || distro_bootpart=1

echo "Boot script loaded from ${devtype} ${devnum}:${distro_bootpart}"

if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}armbianEnv.txt; then
	load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}armbianEnv.txt
	env import -t ${load_addr} ${filesize}
fi

# Re-apply after armbianEnv.txt (it often sets verbosity=1).
setenv verbosity "7"
setenv console "both"
setenv earlycon "on"

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS2,1500000 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlycon=uart8250,mmio32,0xfe660000 ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

# get PARTUUID of first partition on SD/eMMC the boot script was loaded from. Clear
# it first: on a non-mmc devtype, or if the lookup itself fails, U-Boot leaves the
# variable untouched rather than clearing it, so a stale PARTUUID from an earlier
# successful lookup could otherwise be reused below.
setenv partuuid
if test "${devtype}" = "mmc"; then part uuid mmc ${devnum}:${distro_bootpart} partuuid; fi

# armbianEnv.txt normally sets rootdev (UUID=...). If missing: prefer partition 2
# (rootfs) PARTUUID — partuuid above is the *boot* partition and must not be root.
if test -z "${rootdev}"; then
	setenv root_partuuid
	if test "${devtype}" = "mmc"; then part uuid mmc ${devnum}:2 root_partuuid; fi
	if test -n "${root_partuuid}"; then
		setenv rootdev "PARTUUID=${root_partuuid}"
	elif test -n "${partuuid}"; then
		setenv rootdev "PARTUUID=${partuuid}"
	else
		setenv rootdev "/dev/mmcblk0p2"
	fi
fi

# USB3 + cheap Alcor sticks (058f:6387): after U-Boot loads the kernel from
# xHCI, the kernel re-inits the controller and the stick often never comes back
# as a block device (USB2/EHCI works). Disable UAS *and* USB LPM.
# If armbianEnv already set usbstoragequirks (other VID:PIDs), still append Alcor.
if test -z "${usbstoragequirks}"; then
	setenv usbstoragequirks "0x058f:0x6387:u"
else
	setenv usbstoragequirks "${usbstoragequirks},0x058f:0x6387:u"
fi
# rootwait is enough on eMMC; default 30s rootdelay only slows initramfs.
if test -z "${rootdelay}"; then setenv rootdelay "0"; fi
setenv extraargs "${extraargs} usbcore.quirks=058f:6387:k usbcore.autosuspend=-1"

# eDP console (validated on edge hybrid): fbcon on fb0 + fixed panel mode
setenv z96a_displayargs "fbcon=map:0 video=eDP-1:1920x1080@60"
setenv bootargs "root=${rootdev} rootwait rootdelay=${rootdelay} rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs} ${z96a_displayargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"; fi

load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}Image

load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	elif load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
if test "${overlay_error}" = "true"; then
	echo "Error applying DT overlays, restoring original DT"
	load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
else
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr; then
		load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr
		echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
		source ${load_addr}
	fi
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}fixup.scr; then
		load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}fixup.scr
		echo "Applying user provided fixup script (fixup.scr)"
		source ${load_addr}
	fi
fi

booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
